CREATE OR REPLACE NONEDITIONABLE TRIGGER estudiante."DEL_MD_TRIGGERS_V_TRG" AFTER DELETE ON estudiante.MD_VIEWS
FOR EACH ROW 
BEGIN
  DELETE FROM MD_TRIGGERS WHERE MD_TRIGGERS.TABLE_OR_VIEW_ID_FK = :OLD.ID AND MD_TRIGGERS.TRIGGER_ON_FLAG = 'V';
END;
/